name: Scrape and Deploy

on:
  workflow_dispatch: # Manual run
  schedule:
  - cron: '0 0 * * 0'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install depenencies
      run: pip install requests

    - name: Run Python script for scraping (reviews)
      run: |
        cd scripts
        python scrape-for-reviews.py ${{ secrets.GITHUB_TOKEN }}

    - name: Run Python script for scraping (contributors)
      run: |
        cd scripts
        python scrape-for-contributors.py ${{ secrets.GITHUB_TOKEN }}

    - name: Check for changes
      id: git_diff
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        if git diff-index --quiet HEAD; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Commit changes
      if: ${{ steps.git_diff.outputs.changes == 'true' }}
      run: |
          git commit -am "Update review counts"
          git push
  deploy:
    needs: scrape
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: yarn

    - name: Build the site
      run: yarn build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Location from which to grab the files to deploy
        destination_dir: ./dist # Subfolder to deploy to
        publish_branch: deploy  # Branch name to deploy to
        force_orphan: true # Always reset branch to deploy to